//  ClipboardManager.swift
//  ClipboardHistory
//
//  Ядро: мониторинг буфера, история, списки, сохранение

import SwiftUI
import Combine
import AppKit
import Carbon
import ServiceManagement
import CryptoKit
import UniformTypeIdentifiers
import LinkPresentation   // превью ссылок: заголовок + иконка сайта

// MARK: - Менеджер буфера обмена

class ClipboardManager: ObservableObject {
    @Published var history: [ClipboardItem] = [] {
        didSet { scheduleSave() }
    }
    @Published var lists: [String] = [] {
        didSet { saveLists() }
    }
    @Published var smartLists: [SmartList] = [] {
        didSet { saveSmartLists() }
    }
    @Published var snippets: [Snippet] = [] {
        didSet { saveSnippets() }
    }
    @Published var excludedApps: [String] = [] {   // bundle ID приложений-исключений
        didSet { UserDefaults.standard.set(excludedApps, forKey: "excludedApps") }
    }
    @Published var openToken = 0   // меняется при каждом открытии панели (для прокрутки вверх)
    @Published var dockHeight: CGFloat = 600   // актуальная высота панели в режиме дока
    @Published var isPaused = false {   // пауза записи буфера (приватность)
        didSet { AppDelegate.shared?.updateStatusIcon() }
    }

    private var timer: Timer?
    private var cleanupTimer: Timer?
    private var saveWorkItem: DispatchWorkItem?    // отложенное сохранение истории
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private let storageKey = "clipboardHistory"
    private let listsKey = "userLists"

    // Настройки
    private var maxItems: Int        { UserDefaults.standard.integer(forKey: "maxItems") }
    private var savePasswords: Bool  { UserDefaults.standard.bool(forKey: "savePasswords") }
    private var playSound: Bool      { UserDefaults.standard.bool(forKey: "playSound") }
    private var soundOnCapture: Bool { UserDefaults.standard.bool(forKey: "soundOnCapture") }
    private var pastePlainText: Bool { UserDefaults.standard.bool(forKey: "pastePlainText") }
    private var cleanupDays: Int     { UserDefaults.standard.integer(forKey: "cleanupDays") }
    private var captureSoundName: String { UserDefaults.standard.string(forKey: "captureSoundName") ?? "Tink" }
    private var historySoundName: String { UserDefaults.standard.string(forKey: "historySoundName") ?? "Pop" }
    private var hidePasswordLike: Bool { UserDefaults.standard.bool(forKey: "hidePasswordLike") }

    // Маркеры «скрытого» содержимого от менеджеров паролей и т.п.
    private let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),   // стандарт nspasteboard.org
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),        // 1Password
        NSPasteboard.PasteboardType("com.apple.security.password")       // некоторые системные поля
    ]
    private let alwaysIgnoredTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    // Грубая эвристика «похоже на пароль»: одно слово без пробелов,
    // 8–64 символа, с буквами и цифрами (или спецсимволами / разным регистром).
    private func looksLikePassword(_ text: String) -> Bool {
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard t.count >= 8, t.count <= 64 else { return false }
        guard !t.contains(where: { $0 == " " || $0 == "\n" || $0 == "\t" }) else { return false }
        let hasLetter = t.contains { $0.isLetter }
        let hasDigit  = t.contains { $0.isNumber }
        let hasSymbol = t.contains { !$0.isLetter && !$0.isNumber }
        let hasUpper  = t.contains { $0.isUppercase }
        let hasLower  = t.contains { $0.isLowercase }
        return hasLetter && hasDigit && (hasSymbol || (hasUpper && hasLower))
    }

    // Папка для вложений: ~/Library/.../Application Support/ClipboardHistory/Files
    private let attachmentsDirectory: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory,
                                            in: .userDomainMask)[0]
            .appendingPathComponent("ClipboardHistory/Files", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        return base
    }()

    init() {
        UserDefaults.standard.register(defaults: [
            "maxItems": 50,
            "savePasswords": false,
            "playSound": true,
            "soundOnCapture": false,
            "pastePlainText": false,
            "cleanupDays": 0,        // 0 = автоочистка выключена
            "autoPaste": false,
            "captureSoundName": "Tink",
            "historySoundName": "Pop",
            "compactMode": false,
            "panelSize": "medium",
            "panelPosition": "topRight",
            "hidePasswordLike": false,
            "linkPreviews": true,
            "hotkeyKeyCode": 9,                    // V
            "hotkeyModifiers": cmdKey | shiftKey   // ⇧⌘
        ])

        load()
        loadLists()
        loadSmartLists()
        loadSnippets()
        // 📌 — обычный список, существующий по умолчанию (бывшее «закрепление»).
        if !lists.contains("📌") { lists.insert("📌", at: 0) }
        excludedApps = UserDefaults.standard.stringArray(forKey: "excludedApps") ?? []
        cleanupOldItems()

        // Опрос буфера каждые полсекунды (macOS не умеет уведомлять сама).
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
        // Автоочистка по возрасту — раз в час.
        cleanupTimer = Timer.scheduledTimer(withTimeInterval: 3600, repeats: true) { [weak self] _ in
            self?.cleanupOldItems()
        }
    }

    // MARK: Чтение буфера

    private func checkClipboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Пауза записи: изменения буфера игнорируются (но счётчик обновляем,
        // чтобы после снятия паузы не подхватить старое).
        if isPaused { return }

        let types = pasteboard.types ?? []

        // ЛОГИКА БЕЗОПАСНОСТИ.
        // Менеджеры паролей помечают пароль сразу двумя метками:
        // «скрытое» (Concealed) и «временное» (Transient). Поэтому порядок важен:
        // сначала решаем судьбу скрытого содержимого, и только потом
        // отбрасываем прочее временное/автогенерированное.
        let isConcealed = types.contains(where: { concealedTypes.contains($0) })
        let isTransient = types.contains(where: { alwaysIgnoredTypes.contains($0) })

        var sensitive = false
        if isConcealed {
            if savePasswords {
                sensitive = true          // сохраняем, но помечаем и маскируем
            } else {
                return                    // пароли выключены — не записываем
            }
        } else if isTransient {
            return                        // временное (не пароль) не записываем никогда
        }

        // Эвристика «похоже на пароль» (для приложений без меток).
        if !sensitive, hidePasswordLike,
           let s = pasteboard.string(forType: .string), looksLikePassword(s) {
            if savePasswords {
                sensitive = true
            } else {
                return
            }
        }

        // Приложение, из которого только что скопировали (для иконки записи).
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        // Если это приложение-исключение — ничего не записываем.
        if let source, excludedApps.contains(source) { return }

        var added = false
        if types.contains(.fileURL) {
            // Скопированы файлы (например, в Finder) — сохраняем как файлы.
            if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
               !urls.isEmpty {
                added = addFiles(urls, source: source)
            }
        } else if let pngData = pngData(from: pasteboard) {
            added = addImage(pngData, source: source)
        } else if let text = pasteboard.string(forType: .string) {
            // Если есть форматированная версия — сохраняем и её.
            added = addText(text, rtfData: pasteboard.data(forType: .rtf),
                            source: source, sensitive: sensitive)
        }

        if added && soundOnCapture {
            Sounds.play(captureSoundName)
        }
    }

    @discardableResult
    private func addText(_ text: String, rtfData: Data?, source: String?, sensitive: Bool = false) -> Bool {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }

        // Дубликат: сохраняем пин и список, убираем старую запись (и её RTF-файл).
        let old = history.first(where: { $0.kind == .text && $0.text == text })
        if let old { removeAttachmentFiles(old) }
        history.removeAll { $0.kind == .text && $0.text == text }

        var rtfFilename: String? = nil
        if let rtfData {
            let name = UUID().uuidString + ".rtf"
            if (try? rtfData.write(to: attachmentsDirectory.appendingPathComponent(name))) != nil {
                rtfFilename = name
            }
        }

        var item = ClipboardItem.text(text, rtfFilename: rtfFilename)
        item.listName = old?.listName
        item.sourceBundleID = source
        item.isSensitive = sensitive ? true : nil
        // Сохраняем уже загруженное превью при повторном копировании той же ссылки.
        item.linkTitle = old?.linkTitle
        item.faviconFilename = old?.faviconFilename
        history.insert(item, at: 0)
        trimHistory()

        // Ссылка без превью — загружаем заголовок и иконку в фоне.
        if !sensitive, item.linkTitle == nil, let url = linkURL(from: text) {
            fetchLinkPreview(for: item.id, url: url)
        }
        return true
    }

    // MARK: Превью ссылок

    private var linkPreviews: Bool { UserDefaults.standard.bool(forKey: "linkPreviews") }

    private func linkURL(from text: String) -> URL? {
        guard linkPreviews else { return nil }
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains("\n"),
              t.hasPrefix("http://") || t.hasPrefix("https://"),
              let url = URL(string: t) else { return nil }
        return url
    }

    private func fetchLinkPreview(for id: UUID, url: URL) {
        let provider = LPMetadataProvider()
        provider.timeout = 10
        provider.startFetchingMetadata(for: url) { [weak self] metadata, _ in
            guard let self, let metadata else { return }
            let title = metadata.title
            if let iconProvider = metadata.iconProvider {
                _ = iconProvider.loadObject(ofClass: NSImage.self) { object, _ in
                    let icon = object as? NSImage
                    DispatchQueue.main.async {
                        self.applyLinkPreview(id: id, title: title, icon: icon)
                    }
                }
            } else {
                DispatchQueue.main.async {
                    self.applyLinkPreview(id: id, title: title, icon: nil)
                }
            }
        }
    }

    private func applyLinkPreview(id: UUID, title: String?, icon: NSImage?) {
        guard let index = history.firstIndex(where: { $0.id == id }) else { return }
        if let title, !title.isEmpty {
            history[index].linkTitle = title
        }
        if let icon, let tiff = icon.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let name = UUID().uuidString + ".png"
            if (try? png.write(to: attachmentsDirectory.appendingPathComponent(name))) != nil {
                history[index].faviconFilename = name
            }
        }
    }

    // Иконка сайта для записи-ссылки (через общий кэш картинок).
    func loadFavicon(_ item: ClipboardItem) -> NSImage? {
        guard let filename = item.faviconFilename else { return nil }
        let url = attachmentsDirectory.appendingPathComponent(filename)
        return ImageCache.image(at: url, key: filename)
    }

    @discardableResult
    private func addImage(_ pngData: Data, source: String?) -> Bool {
        let hash = SHA256.hash(data: pngData).map { String(format: "%02x", $0) }.joined()

        let old = history.first(where: { $0.imageHash == hash })
        if let old { removeAttachmentFiles(old) }
        history.removeAll { $0.imageHash == hash }

        let filename = UUID().uuidString + ".png"
        do {
            try pngData.write(to: attachmentsDirectory.appendingPathComponent(filename))
        } catch { return false }

        var item = ClipboardItem.image(filename: filename, hash: hash)
        item.listName = old?.listName
        item.sourceBundleID = source
        history.insert(item, at: 0)
        trimHistory()
        return true
    }

    @discardableResult
    private func addFiles(_ urls: [URL], source: String?) -> Bool {
        let paths = urls.map { $0.path }

        let old = history.first(where: { $0.filePaths == paths })
        history.removeAll { $0.filePaths == paths }

        var item = ClipboardItem.file(paths: paths)
        item.listName = old?.listName
        item.sourceBundleID = source
        history.insert(item, at: 0)
        trimHistory()
        return true
    }

    private func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return nil
    }

    // MARK: Копирование обратно в буфер

    func copyToClipboard(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        // Пароль: помечаем буфер «скрытым», чтобы другие менеджеры буфера
        // (и мы сами при повторном опросе) не записали его содержимое.
        if item.isSensitive == true {
            pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        }

        switch item.kind {
        case .text:
            // Сначала RTF (если есть и не включён режим «без форматирования»),
            // потом обычный текст — приложения сами выберут подходящий формат.
            if !pastePlainText,
               let name = item.rtfFilename,
               let rtfData = try? Data(contentsOf: attachmentsDirectory.appendingPathComponent(name)) {
                pasteboard.setData(rtfData, forType: .rtf)
            }
            if let text = item.text {
                pasteboard.setString(text, forType: .string)
            }
        case .image:
            if let image = loadImage(item) {
                pasteboard.writeObjects([image])
            }
        case .file:
            if let paths = item.filePaths {
                let urls = paths.map { URL(fileURLWithPath: $0) as NSURL }
                pasteboard.writeObjects(urls)
            }
        }
        lastChangeCount = pasteboard.changeCount

        if playSound {
            Sounds.play(historySoundName)
        }
    }

    func loadImage(_ item: ClipboardItem) -> NSImage? {
        guard let filename = item.imageFilename else { return nil }
        let url = attachmentsDirectory.appendingPathComponent(filename)
        return ImageCache.image(at: url, key: filename)
    }

    // Копировать несколько записей сразу: их текст объединяется через перенос строки.
    func copyCombined(_ items: [ClipboardItem]) {
        let text = items.compactMap { $0.text }.joined(separator: "\n")
        guard !text.isEmpty else { return }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        // Если среди выбранного есть пароль — помечаем буфер «скрытым».
        if items.contains(where: { $0.isSensitive == true }) {
            pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        }
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        if playSound { Sounds.play(historySoundName) }
    }

    // PNG-данные картинки на диске (для «Сохранить изображение»).
    func imageData(_ item: ClipboardItem) -> Data? {
        guard let filename = item.imageFilename else { return nil }
        return try? Data(contentsOf: attachmentsDirectory.appendingPathComponent(filename))
    }

    private func removeAttachmentFiles(_ item: ClipboardItem) {
        if let name = item.imageFilename {
            ImageCache.drop(name)
            try? FileManager.default.removeItem(at: attachmentsDirectory.appendingPathComponent(name))
        }
        if let name = item.rtfFilename {
            try? FileManager.default.removeItem(at: attachmentsDirectory.appendingPathComponent(name))
        }
        if let name = item.faviconFilename {
            ImageCache.drop(name)
            try? FileManager.default.removeItem(at: attachmentsDirectory.appendingPathComponent(name))
        }
    }

    // MARK: Управление записями

    func trimHistory() {
        // В лимит истории попадают только записи без списка.
        // Всё, что разложено по спискам (включая 📌), от лимита защищено.
        var freeCount = history.filter { $0.listName == nil }.count
        while freeCount > maxItems {
            if let index = history.lastIndex(where: { $0.listName == nil }) {
                removeAttachmentFiles(history[index])
                history.remove(at: index)
                freeCount -= 1
            } else { break }
        }
    }

    // Автоочистка: удаляем записи без списка старше N дней (0 — выключено).
    func cleanupOldItems() {
        let days = cleanupDays
        guard days > 0 else { return }
        let cutoff = Calendar.current.date(byAdding: .day, value: -days, to: Date()) ?? Date()
        let expired = history.filter { $0.listName == nil && $0.date < cutoff }
        guard !expired.isEmpty else { return }
        expired.forEach(removeAttachmentFiles)
        history.removeAll { $0.listName == nil && $0.date < cutoff }
    }

    func assign(_ item: ClipboardItem, toList list: String?) {
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            history[index].listName = list
        }
    }

    func delete(_ item: ClipboardItem) {
        removeAttachmentFiles(item)
        history.removeAll { $0.id == item.id }
    }

    func clearHistory() {
        // Очищаем только записи без списка; разложенное по спискам остаётся.
        history.filter { $0.listName == nil }.forEach(removeAttachmentFiles)
        history.removeAll { $0.listName == nil }
    }

    // MARK: Списки

    func addList(_ name: String) {
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty, !lists.contains(trimmed) else { return }
        lists.append(trimmed)
    }

    func deleteList(_ name: String) {
        lists.removeAll { $0 == name }
        // Записи из удалённого списка не пропадают, просто остаются без списка.
        for index in history.indices where history[index].listName == name {
            history[index].listName = nil
        }
    }

    func renameList(_ oldName: String, to newName: String) {
        let trimmed = newName.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty, !lists.contains(trimmed),
              let i = lists.firstIndex(of: oldName) else { return }
        lists[i] = trimmed
        // Переносим записи в переименованный список.
        for index in history.indices where history[index].listName == oldName {
            history[index].listName = trimmed
        }
    }

    func moveList(from source: IndexSet, to destination: Int) {
        lists.move(fromOffsets: source, toOffset: destination)
    }

    // MARK: Умные списки

    func saveSmartList(_ sl: SmartList) {
        if let i = smartLists.firstIndex(where: { $0.id == sl.id }) {
            smartLists[i] = sl
        } else {
            smartLists.append(sl)
        }
    }

    func deleteSmartList(_ sl: SmartList) {
        smartLists.removeAll { $0.id == sl.id }
    }

    // Ручной текстовый клип — добавить произвольный текст в историю.
    func addManualText(_ text: String) {
        addText(text, rtfData: nil, source: nil)
    }

    private func saveSmartLists() {
        if let data = try? JSONEncoder().encode(smartLists) {
            UserDefaults.standard.set(data, forKey: "smartLists")
        }
    }
    private func loadSmartLists() {
        if let data = UserDefaults.standard.data(forKey: "smartLists"),
           let saved = try? JSONDecoder().decode([SmartList].self, from: data) {
            smartLists = saved
        }
    }

    // MARK: Сниппеты

    func saveSnippet(_ s: Snippet) {
        if let i = snippets.firstIndex(where: { $0.id == s.id }) {
            snippets[i] = s
        } else {
            snippets.append(s)
        }
    }
    func deleteSnippet(_ s: Snippet) {
        snippets.removeAll { $0.id == s.id }
    }
    // Положить произвольный текст в буфер (для вставки сниппета).
    func copyText(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        if playSound { Sounds.play(historySoundName) }
    }
    private func saveSnippets() {
        if let data = try? JSONEncoder().encode(snippets) {
            UserDefaults.standard.set(data, forKey: "snippets")
        }
    }
    private func loadSnippets() {
        if let data = UserDefaults.standard.data(forKey: "snippets"),
           let saved = try? JSONDecoder().decode([Snippet].self, from: data) {
            snippets = saved
        }
    }

    // MARK: Резервная копия

    func exportBackup() -> Data? {
        // Пароли в файл не выгружаем: резервная копия — обычный текстовый JSON.
        let safeHistory = history.filter { $0.isSensitive != true }
        let backup = BackupData(history: safeHistory, lists: lists,
                                smartLists: smartLists, snippets: snippets,
                                excludedApps: excludedApps)
        let encoder = JSONEncoder()
        encoder.outputFormatting = .prettyPrinted
        return try? encoder.encode(backup)
    }

    @discardableResult
    func importBackup(_ data: Data) -> Bool {
        guard let backup = try? JSONDecoder().decode(BackupData.self, from: data) else { return false }
        history = backup.history
        lists = backup.lists
        if !lists.contains("📌") { lists.insert("📌", at: 0) }
        smartLists = backup.smartLists
        snippets = backup.snippets
        excludedApps = backup.excludedApps
        flush()
        return true
    }

    // MARK: Исключения

    func addExcludedApp(_ bundleID: String) {
        guard !bundleID.isEmpty, !excludedApps.contains(bundleID) else { return }
        excludedApps.append(bundleID)
    }

    func removeExcludedApp(_ bundleID: String) {
        excludedApps.removeAll { $0 == bundleID }
    }

    // MARK: Хранение

    private func save() {
        if let data = try? JSONEncoder().encode(history) {
            UserDefaults.standard.set(data, forKey: storageKey)
        }
    }
    // Отложенное сохранение: собираем серию изменений в одну запись на диск.
    private func scheduleSave() {
        saveWorkItem?.cancel()
        let work = DispatchWorkItem { [weak self] in self?.save() }
        saveWorkItem = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.6, execute: work)
    }
    // Немедленно сохранить (например, при выходе из приложения).
    func flush() {
        saveWorkItem?.cancel()
        saveWorkItem = nil
        save()
    }
    private func load() {
        if let data = UserDefaults.standard.data(forKey: storageKey),
           let saved = try? JSONDecoder().decode([ClipboardItem].self, from: data) {
            history = saved
        }
    }
    private func saveLists() {
        UserDefaults.standard.set(lists, forKey: listsKey)
    }
    private func loadLists() {
        lists = UserDefaults.standard.stringArray(forKey: listsKey) ?? []
    }
}
